= ActivityLove =
小さなActivityPub実装

== Features / Habits ==
* ユーザーidに使用できる文字列は `[0-9a-zA-Z_\.]+` です。
* ユーザーidは大文字と小文字が区別されません。

== Setup ==

=== Requirements ===
* Python 3.11以降が必要です

==== 主なバージョン依存要素 ====
* pathlib >= 3.4 (`src/info/config.py`)
* 型ヒント >= 3.5
* async/await >= 3.5
* glob.glob の再帰検索 >= 3.5 (`src/autoroute.py`)
* removeprefix() removesuffix() >= 3.9 (`src/lib/split_id.py`)
* `|` で辞書の合成 >= 3.9 (`src/lib/activityjson.py`)
* match文 >= 3.10 (`src/db/__init__.py`)
* tomllib >= 3.11 (`src/info/config.py`)
* `pyproject.toml` からのパッケージインストール >= pip 19.0

=== Install ===
. ユーザーの作成 (任意) +
少なくともrootユーザーで動かすことはお勧めしません。 +
`# adduser --disabled-password --disabled-login activitylove` +
`$ su - activitylove`

. リポジトリのクローン +
`$ git clone -b (.+) https://github.com/akku1139/activitylove.git` +
Hint: `--depth=1` を使用すると早く終わるでしょう。

. venvの作成 (任意) +
`$ python -m venv .venv` (`.venv` は `.gitignore` でサポートされています)

. 依存パッケージのインストール +
`$ pip install -e.` +
また、任意のASGIサーバーが必要です。 https://techpr.info/python/uvicorn-hypercorn-daphne/[比較をどうぞ] +
`$ pip install (uvicorn|hypercorn|daphne|or other)` (Uvicornは動作確認済み) +
Hint: https://fastapi.tiangolo.com/ja/deployment/manually/[Uvicornを使うなら standard でインストールすれば高速に動きます。] +
設定したデータベースのドライバも必要です。インストールしてください。

. 環境変数の設定 +
`$ . ./env.sh`

. データベースを作成 +
`$ cd migration; python main.py; cd ..`

=== Configuration ===
`config/example.toml` を `config/default.toml` にコピーして編集します。

=== Launch ===
`$ cd src && uvicord main:app` Uvicornの場合

== Update ==
. `$ git pull`
. `$ pip install -r requirements.txt`
. マイグレーション

== LICENSE ==
ActivityLove : A tiny ActivityPub server
Copyright (C) 2023 akku

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as 
published by the Free Software Foundation; either version 3 of the 
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

== Donate ==
寄付をしていただければ開発のやる気につながるかもしれません。 +
XMR: `47UhkFdB4wrH8YGCshYtjPHFmktYdVeQZhHpj6e6Aammcy6cWWALZWJAybA4xFgk94UXsKGKaZtGSB8QwoHrG7ao7wJ62Xs` +
ETH: `0x75790924D5Fb371C29AF81E9816a308500c24538` (Polygonチェーンがおすすめ) +
MONA: `MACYgBCyysdPBxxF8nRbAgM22hkZMETfZk`
