# ? host と baseUrl の区別
# TODO 設定ファイルを元に自動でライブラリインストール

name = "ActivityLove"
description = "小さなActivityPubサーバー"

host = "example.com"

maintainer_name = "akku"
maintainer_email = "akku@example.com"

# 別のところに置くかも
open_registrations = false


theme_color = "#000000"
background_color = "#ffffff"

# アカウントがなかった場合は自動作成
proxy_account_name = "proxy"

# ロールを導入するかも
max_note_text_length = 5000

# URLプレビュー欲しい
# https://github.com/misskey-dev/summaly


[db]
# http://docs.sqlalchemy.org/en/latest/core/engines.html

# When using postgres, mysql, etc.
# "postgres" "sqlite" "mysql" or etc...
dialect = "postgres"
# use asyncio driver
driver = ""
user = "user"
pass = "password"
host = "localhost"
port = 5432
database = "activitylove"

# Use when using sqlite3.
# The base of the path is the project root.
# dialect = "sqlite"
# database = "data/db.sqlite"

# 検討中のオプション。Postgresに存在することを確認。
# ssl = true


[cache]
# "mem" "redis" "memcached" "sqlite" or "none"
# mem は dict Python内
# sqlite:///:memory:
type = "redis"

[cache.redis]
host = "localhost"
port = 6379
# pass = "password"

[cache.memcached]
# TODO たくさんオプションがあったけど後で
host = "localhost"
port = 11211


[drive]
# "fs" "minio" "deta"
type = "minio"

[drive.fs]
dir = "files"

# S3互換のオブジェクトストレージ
# https://github.com/misskey-dev/dolphin/blob/develop/.config/example.yml#L95
[drive.minio]
bucket = "activitylove"
# 突っ込まれるフォルダ
prefix = "files"
baseUrl = "https://minio.example.com/activitylove"
endpoint = "minio.example.com:443"
region = ""
useSSL = true
accessKey = "XntWxJJasACN4Sy32!mqX6n"
secretKey = "B@2JYz!Q$jiY84M6ZsyCV$g"

# 戯言
# https://gitlab.com/-/snippets/3620497
[drive.deta]
key = "Deta Key"


# TODO idの種類を用意
[id]
# uuidもバージョン指定したい
type = "uuid"


# サーバーがHTTPリクエストを送信するときに使用されます。
# IPアドレスを隠したいときなどに有用です。
[proxy]
# "http" "https" "socks4" "socks5" or "none"
type = "socks5"
host = "proxy.example.com"
port = "9050"


# クライアントが使用するプロキシです。
[mediaproxy]
# 大体 encodeURIComponent でどうにかなる。

# "misskey" : https://github.com/misskey-dev/media-proxy
#  https://proxy.misskeyusercontent.com/image.webp?url=https%3A%2F%2F...

# "cors-anywhere" : https://github.com/Rob--W/cors-anywhere
#  https://github.com/Rob--W/cors-anywhere/blob/master/README.md#example

# "suwako-imgproxy" : https://gitler.moe/suwako/imgproxy
#  https://imgproxy.076.moe/{host}/{path}

# "akku-proxy" : https://misskey.04.si/notes/9gcqkfmz7u
#  https://host/proxy/https%3A%2F%2Fmisskey.04.si%2Ffiles%2F307cc7ca-6fff-47b7-b15f-62872b0d6b16

type = "misskey"
# or "none"
baseUrl = "https://mediaproxy.example.com"

[syslog]
use = false
# host = "localhost"
# port = 514
